# Generated by Django 2.1.1 on 2018-09-22 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='dolar_indicator',
            new_name='dollar_indicator',
        ),
    ]
