# Generated by Django 2.1.1 on 2018-09-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapi', '0002_auto_20180921_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinantialIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='query',
            name='dollar_indicator',
        ),
        migrations.RemoveField(
            model_name='query',
            name='tmc_indicator',
        ),
        migrations.RemoveField(
            model_name='query',
            name='uf_indicator',
        ),
        migrations.AddField(
            model_name='query',
            name='finantial_indicators',
            field=models.ManyToManyField(to='djapi.FinantialIndicator'),
        ),
    ]
