# Generated by Django 2.1.1 on 2018-09-23 16:32

from django.db import migrations, models
import djapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('djapi', '0003_auto_20180922_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='end_date',
            field=models.DateField(validators=[djapi.models.min_date, djapi.models.max_date]),
        ),
        migrations.AlterField(
            model_name='query',
            name='start_date',
            field=models.DateField(validators=[djapi.models.min_date, djapi.models.max_date]),
        ),
    ]
